---
bibliography: references.bib
---

# Introduction

We make choices every day. What to eat, whether to take one route to work, and when to go to sleep, are just a few examples. Every decision is associated with consequences. Consequences are inherently rewarding (appetitive), punishing (aversive), or both. To understand the processes involved in human decision-making, we use quantitative frameworks to study choice behavior. These analytic approaches are primarily formalized in three disciplines: economics, psychology, and neuroscience.

In the experimental literature, there are two types of decision contexts described. In "decisions under risk", the decision-maker knows with precision the probability distribution of possible outcomes. For "decisions under uncertainty", the decision-maker must infer the probabilities of potential outcomes. In this thesis, I combine insights from economics, psychology, and neuroscience to propose a neurobiologically-plausible theory of decision-making under risk.

In the first chapter, I introduce notation used throughout my thesis. I then outline the evolution of decision-theory from classical economic models to behavioral economic ones. In the second chapter, I describe the influences of behavioral economic theories on neuroscience research. I then cover the relation between (neuro)biology and behavior. In the third chapter, I propose a new theory of decision-making under risk called 'Counterfactual Predicted Utility Theory' which builds upon the foundational work from chapters one and two. In the fourth chapter, I assess the predictive accuracy of Counterfactual Predicted Utility Theory on human choice data from a sure-bet or gamble task. In chapter five, I conclude my thesis with discussions and next steps.
