--- 
title: "Counterfactuals, Dopamine, and Risky Behavior"
subtitle: "Deriving a neurobiological theory of decision-making under risk"
author: "Jonathan D. Trattner"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
twitter-handle: jdtrat
documentclass: book
bibliography: [packages.bib]
csl: apa-numeric-brackets.csl
link-citations: yes
colorlinks: yes
classoption:
  - oneside
linestretch: 1.5
description: |
  In this thesis, I combine insights from economics, pyschology, and neuroscience to develop 'Counterfactual Predicted Utility Theory' (CPUT) as a neurobiologically-plausible theory of decision-making under risk. CPUT is inspired by the observation that sub-second fluctuations in the levels of the neurotransmitter dopamine seemingly reflect factual and counterfactual information. I propose that people incorporate anticipated counterfactual events when making risky decisions. This leads to behavior that is considered ‘irrational’ from a classical economic perspective as described by Expected Utility Theory (EUT). To assess the predictive accuracy of CPUT, I compared variations of CPUT and EUT on human choice data from a sure bet or gamble task using hierarchical Bayesian modeling techniques. I quantified model fit with multiple methods. This includes comparing marginal likelihood model evidence and leave-one-out cross validation predictive accuracy. I found that CPUT offers a better explanation for the data collected as part of the sure-bet or gamble task while EUT is more likely to generalize to other (similar) datasets. While these results do not provide conclusive evidence favoring CPUT, they suggest a possible role for the integration of counterfactual information in risky decision-making that warrants future investigation.
knit: "bookdown::render_book"
url: 'https\://masters-thesis.jdtrat.com/'
---

```{r include=FALSE}
library(targets)
library(ggtext)
library(flextable)
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'thesis-documents/packages.bib')

knitr::opts_chunk$set(
  fig.align = 'center'
)
```

```{r dedications-acknowledgements, child = if (!knitr::is_latex_output()) here::here('thesis-documents/00_dedication-acknowledgements.md')}
```

```{r abstract, child = if (!knitr::is_latex_output()) here::here('thesis-documents/00_abstract.md')}
```

