---
title: "Introduction"
author: "Jonathan Trattner"
date: "12/2/2020"
bibliography: references.bib
---

# Introduction {#introduction}

Imagine you are in a casino and were randomly selected for a lottery game. There is no cost to you for participating. The rules are simple: the house gives you two options. You can either take \$30 for certain or gamble on an 80% chance of getting \$40 (or nothing). Which would you choose? Why?

Historically, economic theorists held the belief that decision makers ought to act in a way that maximized their expected value--the magnitude of an outcome multiplied by its probability of occurring.[@fox2009] In the decision-making literature, we would represent the casino example with the following notation:

$$\begin{aligned}
\text{Option 1} = (x_{1}, p_{1}) = (\$30, 1) \\
\text{Option 2} = (x_{2}, p_{2}) = (\$40, 0.8) 
\end{aligned}$$

It's easy to see that the expected value of option 2 ($\$40 \times 0.8 = \$32$) is greater than the expected value of option 1 ($\$30 \times 1$), and it would be rational to choose option 2. What if the house offered you a choice between a 50% chance of winning a three-week tour of England, France, and Italy, or a one-week tour of England with certainty? One might assume that the three-week tour is preferred. That presumption discounts individual preferences, however. One person may dislike French and Italian foods, for example. Another may dislike fish & chips and has a desire to learn French. Whatever the case, it is harder to compare the two outcomes as an individual's state might vary.[^1]

[^1]: The casino example is modified from Kahneman and Tversky's paper on Prospect theory. The trip to Europe is directly from it.[@kahneman1979]

As a way to address this limitation, Swiss mathematician Daniel Bernoulli coined the term 'utility' referring to the subjective or "moral value" of a certain outcome in a decision, in lieu of using the objective value.[@bernoulli1954; @fox2009] This concept formed the basis for expected utility theory (EUT), propelled forward by von Neumann and Morgenstern in 1947.[@vonneumann1947] After EUT was axiomatized, its validity was called into question, most notably with the Allais paradox. This suggested that rationality (i.e. maximizing expected value) according to Bernoulli's principle neglects a specific element in the psychology of risk: the variance of individuals' psychological values.[@allais1953]

Alternative theories of decision making were proposed that address some of the limitations of EUT, most notably *prospect theory*.[^2] As we describe next, prospect theory has certain limitations. In this paper, we hope to expound upon it, and other alternatives to EUT, by devising a more intuitive explanation of human decision-making. We call our theory Counterfactually Predicted Utility Theory (CPUT).

[^2]: Although we predominantly focus on prospect theory in this paper, our work was influenced by regret theory[@loomes1982] and salience theory[@bordalo2012]. The former assumes a convex value function that incorporates the feelings of regret and rejoicement for different outcomes. The latter incorporates a linear value function and assumes ordering and diminishing sensitivity properties that affect decision weights.

## Prospect Theory {#prospect-theory}

Kahneman and Tversky (1979) developed *prospect theory* to explain limitations of EUT for simple prospects with monetary outcomes and objective probabilities.[@kahneman1979] They account for a few violations of conventional EUT. Notably, they discuss the certainty effect where individuals overweight outcomes considered certain relative to outcomes considered probable (recall the casino prospect). Kahneman and Tversky also discuss the reflection effect which is where individuals' preferences for positive prospects are the inverse of their preferences for negative prospects (i.e. risk aversion in the gain domain is accompanied by risk seeking in the loss domain).[@kahneman1979][^3]

[^3]: Please note these are general overviews of each theory as it relates to the current paper. For instance, Kahneman and Tversky (1979) also address the Allais paradox and the isolation effect, though those are not the primary focus of this paper. For a more detailed explanation, see each reference.

There are two main takeaways of prospect theory. The first is a value function where the value corresponds to changes in wealth or welfare, rather than final states; it is concave for gains and convex for losses, with losses steeper than gains.[@kahneman1979] The second is a nonlinear weighting of probabilities that leads to overweighting small probabilities and underweighting moderate to high probabilities. [@kahneman1979; @tversky] This weighting function $\pi(.)$ has the property of subcertainty where, for all $0 < p < 1$, $\pi(p) + \pi(1-p) < 1$.

Although prospect theory is one of the leading alternatives to EUT, we believe it ignores an important aspect of human decision making: counterfactual information.

## Counterfactual Thinking {#counterfactual-thinking}

Counterfactual thinking is a mechanism by which the present state of the world is compared to alternative states -- i.e. "what is" vs. "what might have been".[@liu2016; @nealj.roese1997] Revisiting the casino example, how would you feel if you gambled on the \$40 and lost? You could have had \$30 for certain, but forwent that option for a chance at something more. Chances are you would experience a feeling of regret. Had you won \$40, you might experience a feeling of rejoicement. The question becomes: would you account for *potential* feelings of regret or rejoicement when making your decision?

This notion was formally described by Loomes and Sugden with *regret theory*, an alternative to prospect theory.[@loomes1982] The authors make the assumption that individuals can anticipate feelings of rejoicement and regret and will act in a manner to minimize regret and maximize rejoicement.[^4]

[^4]: For the technical treatment of regret theory, please see Loomes and Sugden (1982).

We incorporate aspects of regret theory when developing our own. Specifically, we assume an individual can anticipate feelings of regret and rejoicement via counterfactual information.
